spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/dantal}
    username: ${DB_USER:dantal}
    password: ${DB_PASSWORD:dantal}
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5

logging:
  level:
    root: WARN
    com.dantal: INFO

dantal:
  security:
    jwt:
      secret: ${JWT_SECRET}
