-- Dantal baseline schema — Phase 1 foundation
-- Supports future multi-tenant SaaS via clinic_id on core entities

-- ---------------------------------------------------------------------------
-- Roles (RBAC)
-- ---------------------------------------------------------------------------
CREATE TABLE roles (
    id          SMALLINT     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(50)  NOT NULL,
    description VARCHAR(255),
    created_at  TIMESTAMP  NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_roles_name UNIQUE (name)
);

INSERT INTO roles (name, description) VALUES
    ('SUPER_ADMIN',  'Platform super administrator'),
    ('ADMIN',        'Clinic administrator'),
    ('DOCTOR',       'Doctor'),
    ('DENTIST',      'Dentist'),
    ('RECEPTIONIST', 'Receptionist'),
    ('ASSISTANT',    'Clinical assistant'),
    ('ACCOUNTANT',   'Accountant'),
    ('PATIENT',      'Patient portal user');

-- ---------------------------------------------------------------------------
-- Clinics (multi-branch / multi-tenant ready)
-- ---------------------------------------------------------------------------
CREATE TABLE clinics (
    id              UUID         PRIMARY KEY,
    name            VARCHAR(255) NOT NULL,
    name_en         VARCHAR(255),
    slug            VARCHAR(100) NOT NULL,
    phone           VARCHAR(50),
    email           VARCHAR(255),
    address         TEXT,
    timezone        VARCHAR(64)  NOT NULL DEFAULT 'Asia/Baghdad',
    active          BOOLEAN      NOT NULL DEFAULT TRUE,
    version         BIGINT       NOT NULL DEFAULT 0,
    created_at      TIMESTAMP  NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP  NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_clinics_slug UNIQUE (slug)
);

CREATE INDEX idx_clinics_active ON clinics (active);

-- ---------------------------------------------------------------------------
-- Users
-- ---------------------------------------------------------------------------
CREATE TABLE users (
    id              UUID         PRIMARY KEY,
    clinic_id       UUID         REFERENCES clinics (id) ON DELETE SET NULL,
    email           VARCHAR(255) NOT NULL,
    password_hash   VARCHAR(255) NOT NULL,
    first_name      VARCHAR(100),
    last_name       VARCHAR(100),
    phone           VARCHAR(50),
    active          BOOLEAN      NOT NULL DEFAULT TRUE,
    email_verified  BOOLEAN      NOT NULL DEFAULT FALSE,
    locked_until    TIMESTAMP,
    failed_attempts SMALLINT     NOT NULL DEFAULT 0,
    version         BIGINT       NOT NULL DEFAULT 0,
    created_at      TIMESTAMP  NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP  NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_users_email UNIQUE (email)
);

CREATE INDEX idx_users_clinic_id ON users (clinic_id);
CREATE INDEX idx_users_active    ON users (active);

-- ---------------------------------------------------------------------------
-- User ↔ Role (many-to-many)
-- ---------------------------------------------------------------------------
CREATE TABLE user_roles (
    user_id UUID    NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    role_id SMALLINT NOT NULL REFERENCES roles (id) ON DELETE CASCADE,
    PRIMARY KEY (user_id, role_id)
);

CREATE INDEX idx_user_roles_role_id ON user_roles (role_id);

-- ---------------------------------------------------------------------------
-- Refresh tokens (rotation + revocation)
-- ---------------------------------------------------------------------------
CREATE TABLE refresh_tokens (
    id           UUID         PRIMARY KEY,
    user_id      UUID         NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    token_hash   VARCHAR(255) NOT NULL,
    device_id    VARCHAR(255),
    device_name  VARCHAR(512),
    expires_at   TIMESTAMP  NOT NULL,
    revoked_at   TIMESTAMP,
    replaced_by  UUID         REFERENCES refresh_tokens (id) ON DELETE SET NULL,
    created_at   TIMESTAMP  NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_refresh_tokens_hash UNIQUE (token_hash)
);

CREATE INDEX idx_refresh_tokens_user_id    ON refresh_tokens (user_id);
CREATE INDEX idx_refresh_tokens_expires_at ON refresh_tokens (expires_at);
CREATE INDEX idx_refresh_tokens_active     ON refresh_tokens (user_id, revoked_at);

-- ---------------------------------------------------------------------------
-- Audit log (foundation for compliance)
-- ---------------------------------------------------------------------------
CREATE TABLE audit_logs (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    clinic_id   UUID         REFERENCES clinics (id) ON DELETE SET NULL,
    user_id     UUID         REFERENCES users (id) ON DELETE SET NULL,
    action      VARCHAR(100) NOT NULL,
    entity_type VARCHAR(100),
    entity_id   VARCHAR(100),
    details     JSON,
    ip_address  VARCHAR(45),
    user_agent  VARCHAR(512),
    created_at  TIMESTAMP  NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_audit_logs_clinic_id  ON audit_logs (clinic_id);
CREATE INDEX idx_audit_logs_user_id    ON audit_logs (user_id);
CREATE INDEX idx_audit_logs_created_at ON audit_logs (created_at DESC);
CREATE INDEX idx_audit_logs_action     ON audit_logs (action);
